<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>OrangeHR True Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>fa5ee161-84bc-4c71-b5a4-cfd70a89df7a</testSuiteGuid>
   <testCaseLink>
      <guid>d40373cf-6e33-44ad-ab2c-ac7d18e7de88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC1-Add and Delete Employee in HR Portal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fba215ab-88cb-46e3-bbf9-295040cd878d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a9102c4-5d27-4f39-9a9b-270adc322272</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37145ea1-d511-4ddc-b312-8fe556c8061c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7eeb6ec9-bb36-4697-88ce-f141043f0118</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>747f8f74-5b61-40cb-9353-15e667c33cd2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>78d8b968-41d8-4a85-8f8a-ba95b0971d98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC2-Add Employee and Search in Directory</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>765452ed-f072-4720-a205-df9718db901c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e2d3cd4-4145-461d-8dd9-e2851a5f60bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b9e7c62-eb81-49f1-b866-404dd6a5e2bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7646be10-2e0d-4c2b-b280-37b9ae690977</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb18f4cd-d6d2-4185-a763-830ce6d6563f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d3a76dbb-693b-4164-bc2b-8f4e1f0f0242</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC3-Edit Timesheet Entry in HR Portal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>907a4ba1-9145-4553-9244-40ca082ae5d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d46153e-9e39-4aef-9cad-dbddf81742b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>078e7b73-b35d-48b4-8208-c154c5ef30c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>72de0fa4-467a-4981-86a2-0adedbc1d068</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC4-Delete Employee from Directory in HR Portal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2d384a2-77c4-4c0d-8276-678e74cecc03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>861055ba-92e5-4426-8f44-539475e3920a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4527a610-6c5d-4f88-80d2-3aee34e63b31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8453203-ac5c-4996-88e9-1d5457803647</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>122f9c13-a46e-47bb-bfa6-93447d3023bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AI-Generated/TC5-Logout from HR Portal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c391e1b-a024-47e5-a16f-04f197bbaaad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c73f018-f6ad-450a-9911-016417b3de5d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
