<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2ffba941-e529-4948-b56a-e2316b4bfe37</elementGuidId>
    <imagePath></imagePath>
    <name>input_MiddleName</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/form[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'middleName')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:attr=[placeholder="Middle name"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>middleName</value>
        <webElementGuid>c26fd2aa-836f-4060-b807-0fb3eb5ff448</webElementGuid>
    </webElementProperties>
</WebElementEntity>