<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7d1a6b7a-3757-468f-acf9-abc419e9eefb</elementGuidId>
    <imagePath></imagePath>
    <name>icon_UserAbirMunna</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/header[1]/div[1]/div[3]/ul[1]/li[1]/span[1]/i[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>span &gt;&gt; internal:has-text="Abir Munna"i &gt;&gt; i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>